version: "3.8"

services:
  db:
    image: mysql:8.0                      
    container_name: practice_db           
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass       
      MYSQL_DATABASE: appDB               
      MYSQL_USER: user                   
      MYSQL_PASSWORD: password           
    volumes:
      - db_data:/var/lib/mysql          
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        
    ports:
      - "3306:3306"                       

  web:
    build: ./php                         
    container_name: practice_web
    depends_on:
      - db                                
    volumes:
      - ./www:/var/www/html              
    ports:
      - "8080:80"                        
    restart: unless-stopped

volumes:
  db_data:                               
